upstream event_cluster {
    least_conn;
    server event-service:3001;
}

upstream ticket_cluster {
    least_conn;
    server ticket-service:3002;
}

upstream payment_cluster {
    least_conn;
    server payment-service:3003;
}

upstream notification_cluster {
    least_conn;
    server notification-service:3004;
}

server {
    listen 80;
    client_max_body_size 10M;

    # Lebih spesifik harus di atas — lock ditangani ticket-service
    location ~ ^/events/[0-9]+/lock$ {
        proxy_pass http://ticket_cluster;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Event Service
    location /events {
        proxy_pass http://event_cluster;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Ticket Service
    location /tickets {
        proxy_pass http://ticket_cluster;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Payment Service
    location /payments {
        proxy_pass http://payment_cluster;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Notification Service
    location /notifications {
        proxy_pass http://notification_cluster;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "gateway ok\n";
        add_header Content-Type text/plain;
    }
}
